<script>
$(document).ready(function(e) {
	$('#confdelete').live('click',function()
	{
	if($('#agree').is(':checked'))
	{

	
	 $('#showmesage').html("<p><strong>Your profile being deleted.....</strong></p>").show('slow');
	$('#confdelete').attr("disabled","disabled");
	$.ajax({
		type : 'GET', 
		url: "<?php echo Yii::app()->request->baseUrl;?>/user/profile/Deleteconfirm",
		datatype: "json",
		data: { actiontype:'ajax'},
		success: function(complete){
		if(complete=='success')
		{
			$('#showmesage').html('<p><strong><?php echo UserModule::t('Your profile has been deleted successfully.'); ?></strong>').show('slow');
		setTimeout(function() { 
		
		$('#showmesage').fadeOut('slow'); 
		window.opener.location.reload(); 
		self.close();
		
		}, 5000);

		}else
		{
			$('#showmesage').html('<p><strong><?php echo UserModule::t('Your profile could not be deleted.'); ?></strong>').show('slow');
		setTimeout(function() { $('#showmesage').fadeOut('slow'); }, 10000);

		}
		
		 return false;
			},
		
		})
	
	
	
		
	}else
	{
	$('#showmesage').html('<p><strong><?php echo UserModule::t('Please select the check box.'); ?></strong>').show('slow');
	}
	
	});
	
 });
</script>
<div class="popupmain">
<div class="row">
<textarea name="" cols="" rows="" readonly="readonly">TERMS AND CONDITIONS OF USE

PLEASE READ THE FOLLOWING TERMS AND CONDITIONS CAREFULLY BEFORE USING THIS SITE. By using this site, you signify your agreement to these Terms and Conditions. If you do not agree to these Terms and Conditions, do not use this site. Hasbro may modify these Terms and Conditions at anytime.
Restrictions On Use of Materials

This site is copyright protected. Any textual or graphic material you copy, print, or download is licensed to you by Hasbro, Inc. and/or its subsidiaries ("Hasbro") for your personal, non-commercial home use only, provided that you do not change or delete any copyright, trademark or other proprietary notices.

If you download software from the site, the software, including all files and images, contained in or generated by the software, and accompanying data (together referred to as "Software") are deemed to be licensed to you by Hasbro, for your personal, non-commercial home use only. Hasbro does not transfer either the title or the intellectual property rights to the Software and Hasbro retains full and complete title to the Software as well as all intellectual property rights therein. You may not sell, redistribute or reproduce the Software, nor may you decompile, reverse engineer, disassemble or otherwise convert the Software to a human-perceivable form. All trademarks and logos are owned by Hasbro or its licensors and you may not copy or use them in any manner.

This site is controlled and operated by Hasbro, Inc. from its offices within the State of Rhode Island, United States of America. Hasbro makes no representation that materials in the site are appropriate or available for use in other locations. Those who choose to access this site from other locations do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. Software from this site is subject to U.S. export controls. No software from this site may be downloaded or otherwise exported or reexported into (or to a national or resident of) Cuba, Iraq, Libya, North Korea, Iran, Syria or any other country to which the U.S. has embargoed goods or to anyone on the U.S. Treasury Department's list of Specially Designated National or the U.S. Commerce Department's Table of Deny Orders. By downloading or using the software, you represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list. </textarea>
</div>
<div class="row">

<p><input type="checkbox" id="agree" name="agree"> I have read and agree to the Terms & Conditions.</p>
</div>
<div class="row">
<p class="greenbtn" style="float:right;padding-right:27px;">
<input type="button" id="confdelete" name="confdelete" value=<?php echo UserModule::t('Delete My Profile') ;?>" />
                     <em></em></p>
</div>
<div id="showmesage"></div>
</div>